name: Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
      fail-fast: false
    steps:
    - name: Set up Android SDK
      run: |
        export ANDROID_ARCH="x86_64"
        ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-35;google_apis;$ANDROID_ARCH" platform-tools emulator
        
        # Check and fix AVD folder permissions if on Ubuntu 24.04
        if [[ "${RUNNER_OS}" == "Linux" && -d "$HOME/.android/avd" ]]; then
          echo "Checking and fixing AVD folder permissions..."
          ls -l ~/.android/avd/
          chmod -R 777 ~/.android/avd/
        fi

        ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager create avd --force --name android35 --device "Nexus 5X" --package "system-images;android-35;google_apis;$ANDROID_ARCH"
        ${ANDROID_HOME}/emulator/emulator -list-avds
